GET http://localhost:8080/api/test/all
###
GET http://localhost:8080/api/test/user
###

###
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "username":"sameera1",
    "email":"sameera@gmail.com",
    "password":"12345678",
    "roles":["user","moderator"]
}

###
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
    "username":"sameera",
    "password":"12345678"
}

###
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
    "username":"sameera",
    "password":"12345678a"
}
